application:

  jobQueueKey: ${JOB_QUEUE_KEY}
  processingQueueKey: ${PROCESSING_QUEUE_KEY}

spring:

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  cache:
    type: redis

logging:
  level:
    com.example: INFO

