management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

spring:
  datasource:
    hikari:
      maximum-pool-size: 3

debug: true

logging:
  level:
    root: DEBUG
