application:

  jobQueueKey: jobQueue
  processingQueueKey: processingQueue

spring:

  datasource:
    url: jdbc:h2:file:~/dev-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
